// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wardrobemma.Data;

#nullable disable

namespace Wardrobemma.Migrations
{
    [DbContext(typeof(WardrobeContext))]
    [Migration("20221025200146_ModifiedGarmentTypes")]
    partial class ModifiedGarmentTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GarmentGarmentColour", b =>
                {
                    b.Property<int>("GarmentColoursGarmentColourID")
                        .HasColumnType("int");

                    b.Property<int>("GarmentsGarmentID")
                        .HasColumnType("int");

                    b.HasKey("GarmentColoursGarmentColourID", "GarmentsGarmentID");

                    b.HasIndex("GarmentsGarmentID");

                    b.ToTable("GarmentGarmentColour");
                });

            modelBuilder.Entity("GarmentGarmentMaterial", b =>
                {
                    b.Property<int>("GarmentMaterialsGarmentMaterialID")
                        .HasColumnType("int");

                    b.Property<int>("GarmentsGarmentID")
                        .HasColumnType("int");

                    b.HasKey("GarmentMaterialsGarmentMaterialID", "GarmentsGarmentID");

                    b.HasIndex("GarmentsGarmentID");

                    b.ToTable("GarmentGarmentMaterial");
                });

            modelBuilder.Entity("GarmentGarmentStyle", b =>
                {
                    b.Property<int>("GarmentStylesGarmentStyleID")
                        .HasColumnType("int");

                    b.Property<int>("GarmentsGarmentID")
                        .HasColumnType("int");

                    b.HasKey("GarmentStylesGarmentStyleID", "GarmentsGarmentID");

                    b.HasIndex("GarmentsGarmentID");

                    b.ToTable("GarmentGarmentStyle");
                });

            modelBuilder.Entity("Wardrobemma.Models.Garment", b =>
                {
                    b.Property<int>("GarmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarmentID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DryCleaning")
                        .HasColumnType("bit");

                    b.Property<string>("GarmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GarmentTypeID")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Preferred")
                        .HasColumnType("bit");

                    b.Property<int>("PurchaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Weather")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("GarmentID");

                    b.HasIndex("GarmentTypeID");

                    b.ToTable("Garment", (string)null);
                });

            modelBuilder.Entity("Wardrobemma.Models.GarmentColour", b =>
                {
                    b.Property<int>("GarmentColourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarmentColourID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GarmentColourID");

                    b.ToTable("GarmentColour", (string)null);
                });

            modelBuilder.Entity("Wardrobemma.Models.GarmentGenericType", b =>
                {
                    b.Property<int>("GarmentGenericTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarmentGenericTypeID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("GarmentGenericTypeID");

                    b.ToTable("GarmentGenericType", (string)null);
                });

            modelBuilder.Entity("Wardrobemma.Models.GarmentMaterial", b =>
                {
                    b.Property<int>("GarmentMaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarmentMaterialID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool?>("Natural")
                        .HasColumnType("bit");

                    b.HasKey("GarmentMaterialID");

                    b.ToTable("GarmentMaterial", (string)null);
                });

            modelBuilder.Entity("Wardrobemma.Models.GarmentStyle", b =>
                {
                    b.Property<int>("GarmentStyleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarmentStyleID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("GarmentStyleID");

                    b.ToTable("GarmentStyle", (string)null);
                });

            modelBuilder.Entity("Wardrobemma.Models.GarmentType", b =>
                {
                    b.Property<int>("GarmentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GarmentTypeID"), 1L, 1);

                    b.Property<int?>("GarmentGenericTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("GarmentTypeID");

                    b.HasIndex("GarmentGenericTypeID");

                    b.ToTable("GarmentType", (string)null);
                });

            modelBuilder.Entity("GarmentGarmentColour", b =>
                {
                    b.HasOne("Wardrobemma.Models.GarmentColour", null)
                        .WithMany()
                        .HasForeignKey("GarmentColoursGarmentColourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wardrobemma.Models.Garment", null)
                        .WithMany()
                        .HasForeignKey("GarmentsGarmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GarmentGarmentMaterial", b =>
                {
                    b.HasOne("Wardrobemma.Models.GarmentMaterial", null)
                        .WithMany()
                        .HasForeignKey("GarmentMaterialsGarmentMaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wardrobemma.Models.Garment", null)
                        .WithMany()
                        .HasForeignKey("GarmentsGarmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GarmentGarmentStyle", b =>
                {
                    b.HasOne("Wardrobemma.Models.GarmentStyle", null)
                        .WithMany()
                        .HasForeignKey("GarmentStylesGarmentStyleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wardrobemma.Models.Garment", null)
                        .WithMany()
                        .HasForeignKey("GarmentsGarmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wardrobemma.Models.Garment", b =>
                {
                    b.HasOne("Wardrobemma.Models.GarmentType", "GarmentType")
                        .WithMany("Garments")
                        .HasForeignKey("GarmentTypeID");

                    b.Navigation("GarmentType");
                });

            modelBuilder.Entity("Wardrobemma.Models.GarmentType", b =>
                {
                    b.HasOne("Wardrobemma.Models.GarmentGenericType", "GarmentGenericType")
                        .WithMany("GarmentTypes")
                        .HasForeignKey("GarmentGenericTypeID");

                    b.Navigation("GarmentGenericType");
                });

            modelBuilder.Entity("Wardrobemma.Models.GarmentGenericType", b =>
                {
                    b.Navigation("GarmentTypes");
                });

            modelBuilder.Entity("Wardrobemma.Models.GarmentType", b =>
                {
                    b.Navigation("Garments");
                });
#pragma warning restore 612, 618
        }
    }
}
